from fpdf import FPDF
from datetime import datetime
import io


class IntakePDF(FPDF):
    def header(self):
        self.set_fill_color(29, 158, 117)
        self.rect(0, 0, 210, 28, "F")
        self.set_y(8)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, "Clinical Intake Report", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, "Generated locally - No data transmitted - HIPAA-safe by design", ln=True, align="C")
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Local AI Clinical Intake Agent  |  Page {self.page_no()}", align="C")


def urgency_color(urgency: str):
    u = urgency.lower()
    if "emergency" in u:
        return (227, 75, 74)
    if "urgent" in u:
        return (186, 117, 23)
    return (29, 158, 117)


def section_title(pdf: IntakePDF, text: str):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, text, ln=True)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(3)


def field_row(pdf: IntakePDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(50, 7, label, ln=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(140, 7, str(value))
    pdf.ln(1)


def generate_pdf(report) -> bytes:
    """Take an IntakeReport object and return PDF bytes."""
    pdf = IntakePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    pdf.cell(0, 6, f"Intake completed: {timestamp}", ln=True)
    pdf.ln(4)

    section_title(pdf, "Patient Presentation")
    field_row(pdf, "Chief Complaint:", report.chief_complaint)
    field_row(pdf, "Duration:", report.duration)
    field_row(pdf, "Severity (1-10):", f"{report.severity_score} / 10")
    pdf.ln(2)

    section_title(pdf, "Additional Symptoms")
    if report.additional_symptoms:
        for symptom in report.additional_symptoms:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(8)
            pdf.cell(0, 7, f"- {symptom}", ln=True)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(0, 7, "None reported", ln=True)
    pdf.ln(2)

    section_title(pdf, "History")
    field_row(pdf, "Allergies:", report.allergies)
    field_row(pdf, "Current Medications:", report.current_medications)
    pdf.ln(2)

    section_title(pdf, "Triage Assessment")
    r, g, b = urgency_color(report.suggested_urgency)
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"  Suggested Urgency: {report.suggested_urgency.upper()}", ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, f"Reasoning: {report.urgency_reasoning}")
    pdf.ln(2)

    if report.red_flags:
        section_title(pdf, "Red Flags Detected")
        pdf.set_fill_color(252, 235, 235)
        pdf.set_text_color(163, 45, 45)
        pdf.set_font("Helvetica", "B", 10)
        for flag in report.red_flags:
            pdf.cell(0, 8, f"  ! {flag}", ln=True, fill=True)
            pdf.ln(1)
        pdf.ln(2)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5,
        "DISCLAIMER: This report was generated by a locally-run AI assistant for "
        "informational intake purposes only. It is not a medical diagnosis and does not "
        "replace evaluation by a licensed healthcare provider. All processing occurred "
        "on-device with no external data transmission.")

    output = pdf.output(dest="S")
    if isinstance(output, str):
        return output.encode("latin-1")
    return bytes(output)